### ISSUE TITLE
Gnome Shell crashes with V2.1.1 United Gnome shell theme enabled when some apps are started

### ISSUE THREAD

**Issue by M4gma** [godlyranchdressing/United-GNOME#99] opened 2017-05-27 15:14 UTC
Here it crashes with steam and gnome-tweak-tool for example. Tested on Ubuntu 17.04 and Fedora 25. If on Wayland the system asks you the password again on the login manager, but over X11 the display turns black and recovers to the regular user interface after some seconds.

I'm not sure if this occurs on early versions of United Gnome

**Comment by godlyranchdressing** [comment] 2017-05-27 16:54
Yep. I noticed it as well. It looks like the culprit is actually the CSS rules for the background colors for apps open in dash to dock. I'm not sure why that would crash the _entire Shell_ though. Replicate the problem a number of times and it even kicks you out of the desktop session. At first I thought I just borked my install but then someone mentioned a similar issue and I was able to reproduce it on a live CD. GNOME Web, Rhythmbox, mostly GNOME stack apps but also a couple other apps cause the issue. I noticed it with Geany and Pinta too.

Might need to submit a bug report.

**Comment by privatemajory** [comment] 2017-05-27 17:07
Having this problem too on Debian Stretch. Running apps like System Monitor and Tweak Tool makes the shell crash. When I comment out or remove the lines with `#dashtodockContainer` in the theme CSS there's no crash. Anyway this is a very good theme!

**Comment by godlyranchdressing** [comment] 2017-05-27 17:31
Pushed a fix.

**Closed** 2017-05-28 01:27 UTC
